version: '3'
services:
  jaeger:
    image: jaegertracing/all-in-one:1.41
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    ports:
      - "16686:16686"  # Jaeger UI
      - "4317:4317"    # OTLP gRPC
      - "4318:4318"    # OTLP HTTP
    networks:
      - default
networks:
  default:
    driver: bridge
