version: '3'
services:
  jaeger:
    image: jaegertracing/all-in-one:1.46
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    ports:
      - "16686:16686"  # Jaeger UI
      - "14268:14268"  # Thrift HTTP (для спанов)
    networks:
      - default

networks:
  default:
    driver: bridge

