version: '3'
services:
  jaeger:
    image: jaegertracing/all-in-one:1.41
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - "5775:5775/udp"      # агентский порт
      - "6831:6831/udp"      # агентский порт для данных в формате Thrift
      - "6832:6832/udp"      # агентский порт для данных в формате Thrift
      - "5778:5778"          # здоровье и метрики
      - "16686:16686"        # UI
      - "14250:14250"        # gRPC
      - "14268:14268"        # HTTP
      - "14269:14269"        # здоровье и метрики
      - "9411:9411"          # поддержка Zipkin
