spring:
  application:
    name: metrics-common
  profiles:
    active: default

# Включает трейсинг
#feature-flag:
#  ccc-jaeger:
#    tracing:
#      enabled: true

logging:
  level:
    org.example.metricscommon: DEBUG